### ISSUE TITLE
Move version into tool, and add a top level schema version

### ISSUE THREAD

**Issue by cramatt** [ARPA-H-BDF/bdfkb-schema#15]
Currently tool version is outside of tool and its not clear the version is for the tool itself. 

```
version: "v1.2.3"

tool:
  name: "ClinicalInsight AI"
  repo_url: "https://github.com/healthtech/clinical-insight-ai"
  tool_homepage: "https://clinicalinsight.healthtech.org"
  documentation_url: "https://docs.clinicalinsight.healthtech.org"
  tool_type: "WebApp"
  tool_notes: "AI-powered clinical decision support system for oncology"

```

Under this ticket, adjust the schema like so

```
tool:
  version: "v1.2.3"
  name: "ClinicalInsight AI"
  repo_url: "https://github.com/healthtech/clinical-insight-ai"
  tool_homepage: "https://clinicalinsight.healthtech.org"
  documentation_url: "https://docs.clinicalinsight.healthtech.org"
  tool_type: "WebApp"
  tool_notes: "AI-powered clinical decision support system for oncology"
```

Also consider adding a top level `schema-version` that denotes what version of the schema is used for validation. I know some tools are moving away from this (protobuf or docker-compose for example? ) but is there value here for BDF? Alternatively, if the schema never has breaking changes (taking GraphQL's approach) then this is less needed. `package.json` in Node projects is not versioned, for example.
