### ISSUE TITLE
Tracking schema changes needed

### ISSUE THREAD

**Issue by cramatt** [ARPA-H-BDF/bdfkb-schema#4]
While migrating the initial schema from CRA's collab to this repo, and also while verifying #2 , there were some schema changes I needed to make that I wanted to track here.

# Fix tests

Two issues when running tests via `poetry run python -m unittest discover`

## Missing imports

When running tests via `poetry run python -m unittest discover`, I needed to change the following to prevent errors about `bdfkb-schema/bdftoolbox_performer.yaml` and `bdfkb-schema/bdftoolbox_core.yaml` files not found. 

```
imports:
- linkml:types
# - bdftoolbox_core
# - bdftoolbox_performer
```

## Named Thing

```
  Tool:
    is_a: NamedThing
```

Needed to remove `is_a` since `NamedThing` is not defined in the schema. 

# Generating python classes

Some issues found when generating python and pydantic classes: `gen-python schemas/model_schema.yaml > dev/output/model_schema.py` and `gen-pydantic schemas/model_schema.yaml > dev/output/model_schema_pydantic.py`.

## Prefix

Maybe not the correct change but

```
default_prefix: system-metadata
```

was changed to 

```
default_prefix: schema
```

I think this is because whatever the default prefix is, must be defined in the list here:

```
prefixes:
  linkml: https://w3id.org/linkml/
  schema: http://schema.org/
  xsd: http://www.w3.org/2001/XMLSchema#
  ORCID: http://identifiers.org/orcid/
```

So the alternative (and maybe proper?) fix would be to add `system-metadata` to that list. But we prob want to change that anyway to something like `bdfkb` ? 

## Duplicate defined types

I had to comment out these because I was getting an error 

```
types:
  # string:
  #   base: str
  #   uri: xsd:string
  # integer:
  #   base: int
  #   uri: xsd:integer
  # boolean:
  #   base: Bool
  #   uri: xsd:boolean
  # datetime:
  #   base: XSDDateTime
  #   uri: xsd:dateTime
  # uri:
  #   base: URI
  #   uri: xsd:anyURI
``` 

## Types need uris

For many of the types I needed to add a uri, for example

```
SemanticVersion:
    uri: http://schema.org/
```

## Str to string

For some reason this line: 

```
  Media:
    description: Media resources associated with your tool
    attributes:
      link:
        range: str
```

Needed to change to:

```
Media:
    description: Media resources associated with your tool
    attributes:
      link:
        range: string
```

-----

That's it for now. Once the schema is migrated over to this repo, we should address these items. FYI @jaeddy @alico-cra @cra-ichan
